version: "3.8"

services:
  restaurant_data_svc:
    container_name: order-percona-db
    image: percona:ps-5.6
    restart: unless-stopped
    platform: linux/x86_64
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$ROOT_PASSWORD
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_ORDER_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - type: bind
        source: $BASE_LOCATION/$ORDER_MYSQL_DATA_LOC
        target: /var/lib/mysql
        volume:
          nocopy: true
      - type: bind
        source: $BASE_LOCATION/$ORDER_INITIAL_SCRIPT_LOC
        target: /docker-entrypoint-initdb.d/1.sql
        volume:
          nocopy: true