server: 
  port: ${PORT:20031}
  contextPath: /order
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${DB_SERVICE:localhost}:${DB_PORT:3301}/${DATABASE:orderdb}}
    username: ${SPRING_DATASOURCE_USERNAME:cpandey}
    password: ${SPRING_DATASOURCE_PASSWORD:chandan@1234}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    platform: mysql
    initialization-mode: always  
  jpa: 
    properties:
      javax:
        persistence:
          schema-generation:
           scripts:
            action: none #none, create, drop
            create-source: metadata
            create-target: order_create.sql
              
      hibernate: 
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto : create
        open-in-view: false
        generate_statistics: true
        events:
          log:
            LOG_QUERIES_SLOWER_THAN_MS: 2 
            
management:
  security:
    enabled: false
  health:
    defaults:
      enabled: true
 
            
database: 
  jndiName: jdbc/orders
  url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${DB_SERVICE:localhost}:${DB_PORT:3301}/${DATABASE:orderdb}}
  #url: jdbc:mysql://localhost:3301/orderdb
  type: org.apache.tomcat.jdbc.pool.DataSource
  username: ${SPRING_DATASOURCE_USERNAME:cpandey}
  password: ${SPRING_DATASOURCE_PASSWORD:chandan@1234}
  defaultAutoCommit: true
  defaultReadOnly: false
  driverClassName: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
  maxActive: 10
  maxIdle: 5
  minIdle: 3
  initialSize: 10
  maxWait: 1000
  testOnBorrow: true
  testOnConnect: true 
  testOnReturn: false
  testWhileIdle: false
  validationQuery: SELECT 1 FROM DUAL
  validationQueryTimeout: 1000
  validatorClassName:  
  logAbandoned:  true
  removeAbandoned:  true
  removeAbandonedTimeOut:  30000
  timeBetweenEvictionRunsMillis:  30000
  minEvictableIdleTimeMillis:  30000
  validationInterval:  30000
  jdbcInterceptors:  
     - "org.apache.tomcat.jdbc.pool.interceptor.ConnectionState"
     - "org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer" 
  auth:  
  entityPackageToScan: "com.itlogiclab.restaurant.order.dataaccess.entity"