apiVersion: v1
kind: Service
metadata: 
  name: order-service-node-port
spec: 
  selector:
    app: order-data-pod
  type: NodePort 
  ports: 
    - targetPort: 3306
      nodePort: 32766
      port: 8080